name: Codespell

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  codespell:
    name: Check for misspellings
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Codespell
        uses: codespell-project/actions-codespell@v2
        with:
          check_filenames: true
          ignore_words_file: .codespellignore
          skip: "*.svg"
